### ISSUE TITLE
Hackage release please

### ISSUE THREAD

**Issue by tmcgilchrist** [bitemyapp/hedgehog-checkers#12]
Is it possible to get a hackage release of this library?
Happy to do it myself if you want and do the necessary sharing of permissions etc.

**Comment by bitemyapp** [comment]
I'll add a couple more classes and get it uploaded today.

**Comment by bitemyapp** [comment]
https://hackage.haskell.org/package/hedgehog-checkers and https://hackage.haskell.org/package/hedgehog-checkers-lens are live.

**Comment by tmcgilchrist** [comment]
Thanks 👍
