### ISSUE TITLE
Duplicating work in monoid?

### ISSUE THREAD

**Issue by paraseba** [bitemyapp/hedgehog-checkers#15]
I think the monoid checker is doing too much:

```haskell
semigroup gen
identity mappend mempty gen
associativity mappend gen
monoidSemigroupSame
```

It checks the superclass (semigroup), the fact that `mappend == <>`, but it *also* checkes associativity of mappend, which, up to insuficient testing, should be "guaranteed" by monoidSamegroupSame.

Am I correct? Can we delete the associativity line and save quite a bit of runtime?

**Comment by bitemyapp** [comment]
You can override the default implementation, we have to check it in case someone has different implementations for Semigroup and Monoid. A lamentable state of affairs but possibly also temporary.

Cf. http://hackage.haskell.org/package/base-4.11.1.0/docs/src/GHC.Base.html#Monoid

**Comment by paraseba** [comment]
But, you are already failing if the monoid has a different implementation, when you check:

```haskell
monoidSemigroupSame
```
Why failing for two reasons? The line I'm proposing to delete is

```haskell
associativity mappend gen
```

Can you think of an example implementation that consistently fails the current version but no the one without checking associativity of mappend?

**Comment by bitemyapp** [comment]
>But, you are already failing if the monoid has a different implementation, when you check:

Good point! Property tests not being proofs, there's still cause to do some extra checking but you could argue for the removal of the associativity check for the monoid.
