### ISSUE TITLE
Interest in supporting Binary?

### ISSUE THREAD

**Issue by wpcarro** [bitemyapp/hedgehog-checkers#16]
Trying to see if `hedgehog-checkers` would be interested in supporting the [Binary](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/binary-0.8.5.1/Data-Binary.html) class. I would happily implement it if so.

**Comment by bitemyapp** [comment]
I personally wouldn't want to encourage people using `binary` in general and I don't think it needs to live in this library, it can be a downstream library named `hedgehog-checkers-binary` or similar I think.

Thanks popping in, sorry it wasn't a fit!
