### ISSUE TITLE
Laws for lenses?

### ISSUE THREAD

**Issue by tmcgilchrist** [bitemyapp/hedgehog-checkers#2]
Is this something that would be useful to add into this package?

It would force a dependency on lens or micro-lens.

**Comment by gwils** [comment]
I like this idea. I reckon big lens is the way to go, but I don't think this package - law tests for standard type classes - needs such a bulky dependency. So in my opinion it should be a separate package called something like `hedgehog-checkers-lens`.

**Comment by bitemyapp** [comment]
@gwils that's a good point. I'd like this library to be broadly usable.

**Comment by bitemyapp** [comment]
I need to write more tests/examples, but I consider this fixed:

https://github.com/bitemyapp/hedgehog-checkers/blob/master/hedgehog-checkers-lens/src/Hedgehog/Checkers/Lens/Properties.hs#L5-L9
